# This is a basic workflow to help you get started with Actions

name: Deploy page

# Controls when the workflow will run
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          default: true

      - name: setup rust wasm
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          default: true
          target: wasm32-unknown-unknown
      - name: install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: setup rust cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: repo
          working-directory: exmatriculation
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build site
        run: mkdir site && cd site && ../build.sh
      - name: deploy page
        uses: crazy-max/ghaction-github-status@v2
        with:
          build_dir: site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

