# This is a basic workflow to help you get started with Actions

name: Deploy page

# Controls when the workflow will run
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          default: true
          
      - name: setup rust wasm
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          default: true
          target: wasm32-unknown-unknown
      - name: setup rust cache
        uses: Swatinem/rust-cache@v1.3.0
        with: 
          key: repo
          working-directory: $GITHUB_WORKSPACE/exmatriculation
      - name: install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build site
        run: mkdir site && cd site && ../build.sh
      - name: deploy page
        uses: peaceiris/actions-github-pages@b80a30e9bf3c1ec596532c3813f0aff094f555e2
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: site
         force_orphan: true
          
